FROM dinkydocker/dinky-standalone-server:1.1.0-flink1.18

ADD --chmod=777 https://maven.aliyun.com/repository/central/com/starrocks/flink-connector-starrocks/1.2.9_flink-1.18/flink-connector-starrocks-1.2.9_flink-1.18.jar /opt/dinky/extends/flink1.18/flink/

ADD --chmod=777 https://maven.aliyun.com/repository/central/org/apache/flink/flink-sql-connector-mysql-cdc/3.1.1/flink-sql-connector-mysql-cdc-3.1.1.jar /opt/dinky/extends/flink1.18/flink/

ADD --chmod=777 https://maven.aliyun.com/repository/central/org/apache/flink/flink-connector-jdbc/3.2.0-1.18/flink-connector-jdbc-3.2.0-1.18.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://maven.aliyun.com/repository/central/org/apache/flink/flink-sql-connector-kafka/3.2.0-1.18/flink-sql-connector-kafka-3.2.0-1.18.jar /opt/dinky/extends/flink1.18/flink/

ADD --chmod=777 https://maven.aliyun.com/repository/central/mysql/mysql-connector-java/8.0.27/mysql-connector-java-8.0.27.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://maven.aliyun.com/repository/central/org/apache/paimon/paimon-flink-1.18/0.8.2/paimon-flink-1.18-0.8.2.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://repository.cloudera.com/artifactory/cloudera-repos/org/apache/flink/flink-shaded-hadoop-3-uber/3.1.1.7.2.9.0-173-9.0/flink-shaded-hadoop-3-uber-3.1.1.7.2.9.0-173-9.0.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://maven.aliyun.com/repository/central/org/apache/flink/flink-sql-connector-oracle-cdc/3.1.1/flink-sql-connector-oracle-cdc-3.1.1.jar /opt/dinky/extends/flink1.18/flink/
#ADD --chmod=777 https://maven.aliyun.com/repository/central/com/oracle/ojdbc/ojdbc8/19.3.0.0/ojdbc8-19.3.0.0.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://maven.aliyun.com/repository/central/com/oracle/database/xml/xdb/19.3.0.0/xdb-19.3.0.0.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://repo1.maven.org/maven2/org/apache/paimon/paimon-flink-action/0.8.2/paimon-flink-action-0.8.2.jar /opt/dinky/extends/flink1.18/flink/
RUN mkdir -p /etc/hive/conf && mkdir -p /etc/hadoop/conf 
ENV HADOOP_CONF_DIR=/etc/hadoop/conf HIVE_CONF_DIR=/etc/hive/conf
COPY ./hive-site.xml /etc/hive/conf/
COPY ./hdfs-site.xml ./core-site.xml /etc/hadoop/conf/
#ADD https://repo.maven.apache.org/maven2/org/apache/paimon/paimon-hive-connector-2.1-cdh-6.3/0.8.2/paimon-hive-connector-2.1-cdh-6.3-0.8.2.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://repo1.maven.org/maven2/org/apache/flink/flink-sql-client/1.18.1/flink-sql-client-1.18.1.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://repo1.maven.org/maven2/org/apache/flink/flink-sql-gateway/1.18.1/flink-sql-gateway-1.18.1.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-hive-2.3.9_2.12/1.18.1/flink-sql-connector-hive-2.3.9_2.12-1.18.1.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://maven.aliyun.com/repository/central/org/apache/flink/flink-connector-oracle-cdc/3.1.1/flink-connector-oracle-cdc-3.1.1.jar /opt/dinky/extends/flink1.18/flink/
ADD --chmod=777 https://repo1.maven.org/maven2/com/oracle/database/nls/orai18n/19.3.0.0/orai18n-19.3.0.0.jar /opt/dinky/extends/flink1.18/flink/
COPY ./ojdbc8-19.3.0.0.jar /opt/dinky/extends/flink1.18/flink/
COPY ./dinky-metadata-base-1.1.0.jar /opt/dinky/lib/
